import type { Metadata } from "next";
import { LegalShell } from "@/components/sections/legal-shell";
import { siteConfig } from "@/config/site";

export const metadata: Metadata = {
  title: "Disclaimer",
  description:
    "General disclaimer for information published on the GetNextSite Agency website.",
  alternates: { canonical: `${siteConfig.url}/disclaimer` },
};

export default function DisclaimerPage() {
  return (
    <LegalShell
      eyebrow="Legal"
      breadcrumbs={[
        { name: "Home", url: "/" },
        { name: "Disclaimer", url: "/disclaimer" },
      ]}
      title={<>Disclaimer</>}
      updated="January 2026"
    >
      <h2>1. General information only</h2>
      <p>
        The content published on{" "}
        <a href={siteConfig.url}>{siteConfig.url.replace(/^https?:\/\//, "")}</a>{" "}
        is for general informational purposes only. It does not constitute
        legal, financial, medical, tax, or professional advice for your
        specific situation.
      </p>

      <h2>2. No guarantees of outcomes</h2>
      <p>
        Case studies, testimonials and statistics published on this site
        represent actual results achieved by specific clients under specific
        conditions. They are not a guarantee of the results you will achieve.
        Individual outcomes depend on many variables including market
        conditions, industry, effort, and third-party factors outside our
        control.
      </p>

      <h2>3. External links</h2>
      <p>
        Our website may contain links to third-party sites. We do not
        endorse, monitor, or take responsibility for the content, policies or
        practices of those sites. Access to external content is at your own
        risk.
      </p>

      <h2>4. AI-generated content</h2>
      <p>
        Some responses generated by AI features we provide or embed may be
        inaccurate or out of date. Always verify important information with a
        qualified human professional before acting on it.
      </p>

      <h2>5. Availability</h2>
      <p>
        We aim for 99.9% uptime on hosted services but cannot guarantee
        uninterrupted access. Scheduled maintenance is communicated in
        advance where possible.
      </p>

      <h2>6. Errors and omissions</h2>
      <p>
        We make reasonable efforts to keep information on this site accurate
        and current. We accept no liability for errors, omissions or
        subsequent changes. Please contact us if you spot something out of
        date.
      </p>

      <h2>7. Contact</h2>
      <p>
        <a href={`mailto:${siteConfig.contact.email}`}>
          {siteConfig.contact.email}
        </a>
      </p>
    </LegalShell>
  );
}
